AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Resources:
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Prepare a member account for leaving the organization
      Runtime: nodejs8.10
      CodeUri: leave-organization-preparation.zip
      Handler: index.handler
      MemorySize: 1024
      Timeout: 30
      Policies:
        - AmazonS3FullAccess
        - AdministratorAccess
